import { User, Company } from '../types';

export const demoUsers: User[] = [
    {
        id: '1',
        fullName: 'John De Silva',
        email: 'johnde@example.com',
        role: 'ADMIN',
        isEmailVerified: true,
        createdAt: '2024-01-10T08:00:00Z',
        companyCount: 3,
        employeeCount: 28,
    },
    {
        id: '2',
        fullName: 'Alex Morgan',
        email: 'alex@example.com',
        role: 'ADMIN',
        isEmailVerified: true,
        createdAt: '2024-01-11T09:30:00Z',
        companyCount: 3,
        employeeCount: 28,
    },
    {
        id: '3',
        fullName: 'Samantha Lee',
        email: 'samantha@example.com',
        role: 'ADMIN',
        isEmailVerified: true,
        createdAt: '2024-01-12T10:15:00Z',
        companyCount: 3,
        employeeCount: 28,
    },
    {
        id: '4',
        fullName: 'Daniel Perera',
        email: 'daniel@example.com',
        role: 'ADMIN',
        isEmailVerified: true,
        createdAt: '2024-01-13T11:00:00Z',
        companyCount: 3,
        employeeCount: 28,
    },
    {
        id: '5',
        fullName: 'Nimal Fernando',
        email: 'nimal@example.com',
        role: 'ADMIN',
        isEmailVerified: true,
        createdAt: '2024-01-14T12:45:00Z',
        companyCount: 3,
        employeeCount: 28,
    },
    {
        id: '6',
        fullName: 'Kamal Silva',
        email: 'kamal@example.com',
        role: 'ADMIN',
        isEmailVerified: true,
        createdAt: '2024-01-15T14:20:00Z',
        companyCount: 3,
        employeeCount: 28,
    },
];

export const demoCompanies: Company[] = [
    {
        id: 'c1',
        name: 'ABC (Pvt) Ltd',
        email: 'contact@abc.com',
        address: '123 Main St, Colombo',
        contactNumber: '0112345678',
        departments: ['HR', 'IT'],
        ownerId: '1',
        employeesCount: 1234,
        subscriptionPlan: 'Enterprise Plan',
        status: 'Active',
        createdAt: '2023-12-01T10:00:00Z',
    },
    {
        id: 'c2',
        name: 'XYZ Solutions',
        email: 'hi@xyz.com',
        address: '456 Business Rd, Kandy',
        contactNumber: '0812345678',
        departments: ['Sales', 'Support'],
        ownerId: '2',
        employeesCount: 1234,
        subscriptionPlan: 'Enterprise Plan',
        status: 'Active',
        createdAt: '2023-12-05T11:00:00Z',
    },
    {
        id: 'c3',
        name: 'Global Tech',
        email: 'info@globaltech.com',
        address: '789 Innovation Ave, Galle',
        contactNumber: '0912345678',
        departments: ['Dev', 'Test'],
        ownerId: '3',
        employeesCount: 1234,
        subscriptionPlan: 'Enterprise Plan',
        status: 'Inactive',
        createdAt: '2023-12-10T09:00:00Z',
    },
    {
        id: 'c4',
        name: 'Smart Systems',
        email: 'hello@smart.com',
        address: '101 Smart Plaza, Matara',
        contactNumber: '0412345678',
        departments: ['Admin'],
        ownerId: '4',
        employeesCount: 1234,
        subscriptionPlan: 'Enterprise Plan',
        status: 'Trial',
        createdAt: '2024-01-05T14:00:00Z',
    },
];
